const $ = (id) => document.getElementById(id);

const LIMITS = { maxFiles: 2000, maxFileBytes: 10 * 1024 * 1024, maxTotalBytes: 30 * 1024 * 1024 };
const state = { step: 'source', chapters: [], schedule: [], page: null, cancelled: false };
const steps = ['source', 'schedule', 'page'];
const chapterPattern = /^第[一二三四五六七八九十百千万零〇两0-9０-９]+[章节回]\s*(.*)$/;

function setStep(step) { state.step = step; steps.forEach((name, index) => { $(`${name}View`).classList.toggle('active', name === step); const marker = document.querySelector(`[data-step="${name}"]`); marker.classList.toggle('active', name === step); marker.classList.toggle('done', index < steps.indexOf(step)); }); $('prevButton').disabled = steps.indexOf(step) === 0; $('nextButton').disabled = steps.indexOf(step) === steps.length - 1 || !state.schedule.length; }
function setFooter(message) { $('footerStatus').textContent = message; }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char])); }
function nextFrame() { return new Promise((resolve) => requestAnimationFrame(resolve)); }
function normalizeText(text) { return String(text || '').replace(/^\uFEFF/, '').replace(/\u0000/g, '').replace(/\r\n?/g, '\n').split('\n').map((line) => line.replace(/[ \t\u00A0]+$/g, '').replace(/^[ \t\u00A0]+/g, '')).join('\n').replace(/\n[ \t\u00A0]*\n+/g, '\n').trim(); }
function cleanChapterTitle(title) {
  const raw = String(title || '').replace(/^\s*#+\s*/, '').trim();
  const match = raw.match(/^第\s*([0-9０-９一二三四五六七八九十百千万零〇两]+)\s*[章节回]\s*(.*)$/);
  if (!match) return raw.replace(/[ \t\u00A0]+/g, ' ').trim();
  const number = match[1];
  const repeatedPrefix = new RegExp(`^(?:第\\s*${number}\\s*[章节回]\\s*)+`);
  const rest = match[2].replace(repeatedPrefix, '').replace(/[ \t\u00A0]+/g, ' ').trim();
  return `第${number}章${rest ? ` ${rest}` : ''}`;
}
function removeLeadingDuplicateTitle(content, title) { const lines = normalizeText(content).split('\n'); const wanted = cleanChapterTitle(title).replace(/\s+/g, ''); while (lines.length && !lines[0].trim()) lines.shift(); if (lines.length) { const first = cleanChapterTitle(lines[0]).replace(/\s+/g, ''); if (first === wanted || (first.startsWith(wanted) && first.length <= wanted.length + 30)) lines.shift(); } return normalizeText(lines.join('\n')); }
function extractChapterHeading(raw) { const source = String(raw || '').trim(); const hasMarkdownHeading = /^#+\s*/.test(source); const line = source.replace(/^#+\s*/, ''); if (!chapterPattern.test(line)) return ''; if (!hasMarkdownHeading && (line.length > 80 || /[。！？；]$/.test(line))) return ''; return line; }

function parseChapterNumber(title) { const match = title.match(/^第\s*([0-9０-９一二三四五六七八九十百千万零〇两]+)\s*[章节回]/); if (!match) return 0; const digits = match[1].replace(/[０-９]/g, (char) => String.fromCharCode(char.charCodeAt(0) - 0xfee0)); if (/^\d+$/.test(digits)) return Number(digits); const map = { 零: 0, 〇: 0, 一: 1, 二: 2, 两: 2, 三: 3, 四: 4, 五: 5, 六: 6, 七: 7, 八: 8, 九: 9 }; const units = { 十: 10, 百: 100, 千: 1000, 万: 10000 }; let total = 0; let section = 0; let number = 0; for (const char of digits) { if (char in map) { number = map[char]; continue; } const unit = units[char]; if (!unit) continue; if (unit === 10000) { section += number; total += (section || 1) * unit; section = 0; } else section += (number || 1) * unit; number = 0; } return total + section + number; }
function addDays(date, amount) { const next = new Date(date); next.setDate(next.getDate() + amount); return next; }
function fmtDate(date) { const p = (n) => String(n).padStart(2, '0'); return `${date.getFullYear()}-${p(date.getMonth() + 1)}-${p(date.getDate())}`; }
function fmtTime(date) { return `${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`; }

function appendChaptersFromText(chapters, fileName, text) {
  const normalized = normalizeText(text); const lines = normalized.split('\n'); let current = null;
  const push = () => { if (!current) return; const content = removeLeadingDuplicateTitle(current.content.join('\n'), current.title); if (content) chapters.push({ ...current, title: cleanChapterTitle(current.title), content, chars: (content.match(/[一-鿿]/g) || []).length }); current = null; };
  for (const raw of lines) { const heading = extractChapterHeading(raw); if (heading) { push(); current = { title: heading, number: parseChapterNumber(heading), content: [], source: fileName }; } else if (current) current.content.push(raw); }
  push();
  if (!chapters.some((chapter) => chapter.source === fileName) && normalized) { const baseName = String(fileName).split(/[\\/]/).pop() || fileName; const title = baseName.replace(/\.txt$/i, '').trim(); const content = removeLeadingDuplicateTitle(normalized, title); chapters.push({ title: cleanChapterTitle(title), number: parseChapterNumber(title), content, chars: (content.match(/[一-鿿]/g) || []).length, source: fileName }); }
}

async function readTextFile(file, fileName, totalBytes) { if (file.size > LIMITS.maxFileBytes) throw new Error(`${fileName} 超过单文件 10 MB 限制`); if (totalBytes + file.size > LIMITS.maxTotalBytes) throw new Error('正文总大小超过 30 MB 限制'); return { fileName, text: await file.text(), bytes: file.size }; }
async function processFiles(fileEntries, label) { if (!fileEntries.length) { state.chapters = []; state.schedule = []; renderChapters(); renderSchedule(); $('sourceStatus').textContent = '所选目录没有返回 TXT 文件，请确认 TXT 位于该目录或子目录中。'; setFooter('没有读取到 TXT'); return; } state.cancelled = false; state.chapters = []; let totalBytes = 0; const skipped = []; $('novelFiles').disabled = true; $('novelDirectory').disabled = true; $('cancelButton').hidden = false; try { for (let index = 0; index < fileEntries.length; index++) { if (state.cancelled) break; if (index >= LIMITS.maxFiles) { skipped.push('超过最多 2000 个文件'); break; } const entry = fileEntries[index]; try { const result = await readTextFile(entry.file, entry.name, totalBytes); totalBytes += result.bytes; appendChaptersFromText(state.chapters, result.fileName, result.text); } catch (error) { skipped.push(error.message); } $('sourceStatus').textContent = `${label}：${index + 1}/${fileEntries.length} 个 TXT，已识别 ${state.chapters.length} 章`; await nextFrame(); } state.chapters.sort((a, b) => (a.number || Number.MAX_SAFE_INTEGER) - (b.number || Number.MAX_SAFE_INTEGER) || a.source.localeCompare(b.source, 'zh-CN', { numeric: true })); state.schedule = computeSchedule(state.chapters); renderChapters(); renderSchedule(); $('sourceStatus').textContent = state.cancelled ? `已取消，保留 ${state.chapters.length} 章。` : `已扫描 ${fileEntries.length} 个 TXT，识别 ${state.chapters.length} 章，待上传 ${state.schedule.length} 章。`; setFooter(state.cancelled ? '读取已取消' : '章节已解析'); if (skipped.length) console.warn('[Tomato Uploader Assistant] skipped files', skipped.slice(0, 20)); } finally { $('novelFiles').disabled = false; $('novelDirectory').disabled = false; $('cancelButton').hidden = true; } }

function computeSchedule(chapters) { const startChapter = Math.max(1, Number($('startChapter').value) || 1); const selected = chapters.filter((chapter) => !chapter.number || chapter.number >= startChapter); const dailyLimit = Math.max(1, Number($('dailyWordLimit').value) || 10000); const chapterLimit = Math.max(1, Number($('dailyChapterLimit').value) || 3); const start = $('startDate').value ? new Date(`${$('startDate').value}T00:00:00`) : new Date(); const [hours, minutes] = ($('dailyPublishTime').value || '07:00').split(':').map(Number); let day = new Date(start); let words = 0; let count = 0; return selected.map((chapter) => { if (count >= chapterLimit || (words + chapter.chars > dailyLimit && words > 0)) { day = addDays(day, 1); words = 0; count = 0; } const date = new Date(day); date.setHours(hours, minutes, 0, 0); words += chapter.chars; count++; return { ...chapter, date: fmtDate(date), time: fmtTime(date) }; }); }
function renderChapters() { $('chapterCount').textContent = `${state.schedule.length} 章`; $('chapterPreview').innerHTML = state.schedule.slice(0, 30).map((chapter, index) => `<div class="preview-item"><span class="index">${String(index + 1).padStart(2, '0')}</span><span class="title">${escapeHtml(chapter.title)}</span><small>${chapter.chars} 字</small></div>`).join(''); if (state.schedule.length > 30) $('chapterPreview').insertAdjacentHTML('beforeend', `<p class="status-line">仅显示前 30 章，实际待上传 ${state.schedule.length} 章。</p>`); $('nextButton').disabled = steps.indexOf(state.step) === steps.length - 1 || !state.schedule.length; }
function renderSchedule() { const days = new Set(state.schedule.map((chapter) => chapter.date)); $('dayCount').textContent = `${days.size} 天`; const totalChars = state.schedule.reduce((sum, chapter) => sum + chapter.chars, 0); $('scheduleSummary').className = 'summary-card'; $('scheduleSummary').innerHTML = `<strong>${state.schedule.length} 章</strong><span>${totalChars} 字 · ${days.size} 天完成 · 从第 ${$('startChapter').value || 1} 章开始</span>`; $('scheduleList').innerHTML = state.schedule.slice(0, 60).map((chapter) => `<div class="schedule-item"><span class="date">${chapter.date}</span><span class="title">${escapeHtml(chapter.title)}</span><small>${chapter.time}</small></div>`).join(''); }
async function sendToPage(message) { const [tab] = await chrome.tabs.query({ active: true, currentWindow: true }); if (!tab?.id || !/^https:\/\/(fanqienovel\.com|writer\.fanqienovel\.com)\//.test(tab.url || '')) throw new Error('当前标签页不是番茄作者后台页面。'); return chrome.tabs.sendMessage(tab.id, message); }
async function selectIndividualFiles(event) { await processFiles([...event.target.files].filter((file) => /\.txt$/i.test(file.name)).map((file) => ({ file, name: file.name })), '正在读取文件'); event.target.value = ''; }
async function selectDirectoryFiles(event) { const selected = [...(event.target.files || [])]; $('sourceStatus').textContent = `目录已返回 ${selected.length} 个文件，正在筛选 TXT…`; const entries = selected.filter((file) => /\.txt$/i.test(file.name)).map((file) => ({ file, name: file.webkitRelativePath || file.name })); try { await processFiles(entries, '正在读取目录'); } catch (error) { $('sourceStatus').textContent = `目录读取失败：${error.message}`; setFooter('读取失败'); } finally { event.target.value = ''; } }

$('novelFiles').addEventListener('change', selectIndividualFiles); $('novelDirectory').addEventListener('change', selectDirectoryFiles); $('novelDirectory').addEventListener('cancel', () => { $('sourceStatus').textContent = '已取消选择目录。'; setFooter('未选择目录'); }); $('cancelButton').addEventListener('click', () => { state.cancelled = true; setFooter('正在停止读取…'); }); $('scheduleButton').addEventListener('click', () => { state.schedule = computeSchedule(state.chapters); renderChapters(); renderSchedule(); setFooter('排期已更新'); });
$('startChapter').addEventListener('change', () => { state.schedule = computeSchedule(state.chapters); renderChapters(); renderSchedule(); chrome.storage.local.set({ startChapter: $('startChapter').value }); });
$('inspectButton').addEventListener('click', async () => { try { state.page = await sendToPage({ type: 'inspect-page' }); $('connectionDot').classList.add('connected'); $('pageBadge').textContent = '已连接'; $('pageInfo').className = 'page-card'; $('pageInfo').innerHTML = `<strong>${escapeHtml(state.page.title || '未命名页面')}</strong><code>${escapeHtml(state.page.url)}</code><p>${state.page.inputs.length} 个输入项 · ${state.page.buttons.length} 个按钮</p>`; $('debugOutput').textContent = JSON.stringify(state.page, null, 2); $('fillButton').disabled = !state.schedule.length; setFooter('页面已识别'); } catch (error) { $('pageInfo').textContent = error.message; setFooter('连接失败'); } });
$('fillButton').addEventListener('click', async () => { if (!state.schedule.length) return; try { const result = await sendToPage({ type: 'fill-chapter', chapter: state.schedule[0] }); if (!result.ok) throw new Error(result.error || '填写失败'); $('pageInfo').innerHTML = `<strong>${escapeHtml(result.message)}</strong><p>标题：${escapeHtml(result.title || '')}</p><p>正文：${result.contentLength || 0} 字</p>`; setFooter('已填写，请检查页面'); } catch (error) { setFooter(error.message); } });
$('prevButton').addEventListener('click', () => setStep(steps[Math.max(0, steps.indexOf(state.step) - 1)])); $('nextButton').addEventListener('click', () => { if (!state.schedule.length) { setFooter('请先选择目录并识别章节'); return; } setStep(steps[Math.min(steps.length - 1, steps.indexOf(state.step) + 1)]); });
(async () => { const fields = ['dailyWordLimit', 'dailyChapterLimit', 'startChapter', 'startDate', 'dailyPublishTime']; const saved = await chrome.storage.local.get(fields); for (const key of fields) if (saved[key] != null) $(key).value = saved[key]; setStep('source'); })();
